### ISSUE TITLE
Getting error Newsstand Icon file missing when trying to submit to Appstore

### ISSUE THREAD

**Issue by dkamdar** [Simbul/baker#1212]
Anyone got this (screenshot attached below) while trying to submit on the App Store?

I checked the "newsstand-app-icon.imageset" in the "BakerAssets.xcassets" folder and I have the files there. Is there a link broken or missing?

There seems to be similar question on Stack Overflow as well thats not answered - http://stackoverflow.com/questions/19618866/error-while-validating-baker-framework-missing-newsstand-icon-file/19996289#19996289

![screen shot 2013-11-15 at 3 01 12 am](https://f.cloud.github.com/assets/1485304/1548542/e6c8179e-4dcc-11e3-9b4c-e72bdd8d3fd6.png)

**Comment by fcontreras** [comment]
same here..

**Comment by dkamdar** [comment]
Resolved it by moving newsstand-app-icon.png outside of Assets Catalog folder to the main folder. Also updated #1124 (with screenshot of folder structure where png needs to be).

**Comment by rlarrett** [comment]
I am getting the same error when I try to validate my app. If I delete the 'newsstand-app-icon' string from the info.plist the app validates, but gets rejected by iTunes Connect. I tried moving the icons to the main folder per @dkamdar but validation still fails. I am using the 4.2 version of Baker.
![error](https://f.cloud.github.com/assets/367918/1847471/47756caa-764e-11e3-8015-5b6d1ec48ebf.jpg)

**Comment by folletto** [comment]
Hi. :)
Please don't post on closed issues. Create a new one if you have a problem, otherwise it's very difficult to keep track and help. :)

Also, this issue tracker is not in use anymore. 
To open a new one, please use the new tracker for Baker Framework, it moved a few months ago:
https://github.com/BakerFramework/baker/issues

:)

**Comment by rlarrett** [comment]
Apologies. I did in fact already post on the new tracker, thanks.
