### ISSUE TITLE
internal links in a page

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#390]
hi all,
now i have another weird link problem. 
i have a page which has 286 different links to the anchors in the same page,
i followed https://github.com/Simbul/baker/wiki/Managing-links-and-urls to create links, however it does not work.
links go to a place in the same page but not the anchor that i wanted
i tried `<a href="Sayfa-02.html#BAKARA-1"><k1>1: Elif, lâm, mim.</k1></a>` not worked
i tried `<a href="#BAKARA-1"><k1>1: Elif, lâm, mim.</k1></a>` also not worked.
her comes the weird part.... this all works on safari, firefox, and chrome. but does not work on simulator and the device..
i am using Baker's latest release downloaded from github
the html file is here for your reference http://dl.dropbox.com/u/51424384/book/Sayfa-02.html 
i would appreciate if you can advice
thanks

**Comment by Xm4s** [comment]
Hi bahmet,

I'm sorry but I wasn't able to reproduce the issue, I tried your code with Baker and anchors worked as expected.
Can you try again in Xcode and report what the debug console logs when you click an anchor?

**Comment by bahmet** [comment]
hi xm4s,
i am using xcode 4.3.1,  latest baker downloaded from github (Simbul-baker-bb0203f is the file name) , rendering mode default (screenshot). here is the log when i clicked to the anchored link.,
```2012-04-19 12:54:53.993 Türkçe Açıklamalı Kuran-ı Kerim[290:15203] • Should webView load the page ?
2012-04-19 12:54:53.995 Türkçe Açıklamalı Kuran-ı Kerim[290:15203] Reloading index from bundle
2012-04-19 12:54:53.997 Türkçe Açıklamalı Kuran-ı Kerim[290:15203]     Page is current page and current page IS NOT delaying loading --> handle clicked link: file:///Users/bahmet/Library/Application%20Support/iPhone%20Simulator/5.0/Applications/E4317225-2C4F-4281-9D44-7F47AABE3351/Tu%CC%88rkc%CC%A7e%20Ac%CC%A7%C4%B1klamal%C4%B1%20Kuran-%C4%B1%20Kerim.app/book/Sayfa-02.html#BAKARA-11
2012-04-19 12:54:54.000 Türkçe Açıklamalı Kuran-ı Kerim[290:15203]     Page is a link with scheme file:// --> load internal link
2012-04-19 12:54:54.002 Türkçe Açıklamalı Kuran-ı Kerim[290:15203] • Check if page has changed
2012-04-19 12:54:54.004 Türkçe Açıklamalı Kuran-ı Kerim[290:15203] • Scrolling page down to 11854

```
thanks a lot
regards

```

**Comment by Xm4s** [comment]
Uhm, I see no problems there ... the line 

> 2012-04-19 12:54:54.004 Türkçe Açıklamalı Kuran-ı Kerim[290:15203] • Scrolling page down to 11854

means that the js command to scroll down the page to the element referenced by the anchor is correctly dispatched.

My advice is to try turning off all the scripts on the page and see if the anchor works.
If that's the case, then turning them on one by one and should reveal which of them is the cause of the problem.

**Comment by FranG** [comment]
At first: great stuff, you provide with baker!

Same issue here: in our really simple demo ( http://publishing.dev.afm-koeln.de/hagebau/book/k5.html , 5 JPEGs in line ) the anchors won't work poperly on the iDevices. Every second tab works fine, but the first one leads to a false page. The browserside works fine.
The error occurs only when hyperlinking within the same page. Sometimes it seems, the the app jumps one page to far (scrolling down to...).

For testing i commented this code out in "RootViewController.m", line 1040 ff.

```
            if ([[url scheme] isEqualToString:@"file"])
            {
                // ****** Handle: file://
                NSLog(@"    Page is a link with scheme file:// --> load internal link");

                anchorFromURL  = [[url fragment] retain];
                NSString *file = [[url relativePath] stringByReplacingPercentEscapesUsingEncoding:NSUTF8StringEncoding];

                int page = [pages indexOfObject:file];
                if (page == NSNotFound)
                {
                    // ****** Internal link, but not one of the book pages --> load page anyway
                    return YES;
                }

                page = page + 1;
                if (![self changePage:page] && ![webView isEqual:indexViewController.view])
                {
                    if (anchorFromURL == nil) {
                        return YES;
                    }

                    [self handleAnchor:YES];                        
                }
            }
```

Result: the first tab on a link doesn't do anything (in most cases...) an the second one is correct.

Frank

**Comment by folletto** [comment]
@FranG did you try using explicit `<a name="keyword">`? Does it work reliably with that? :)

**Comment by FranG** [comment]
@folletto No, won't work. I tried both: Linking to 

div id="keyword" 
and 
a name="keyword"

 Even with the a tag wrapped around an image. The first tap leads always to a position (i.e. page) which is to far down in the same page. In my case (portrait) exactly 1024 px to "far". Moving back and tapping for a second time will jump to the correct position.
I don't exactly understand how the taps, klicks are stored within Baker.

**Comment by folletto** [comment]
@FranG the problem is that it's not Baker at all. Baker handles just the page switch - if you link one file from another - but everything else is builtin WebKit. We can't do much on that. We'll try to have a look, but for now it seems a bug in UIWebView... :/

**Comment by Simbul** [comment]
Hi @FranG I just managed to reproduce (and hotfix) the issue.

Looks like it's a miscalculation in the `goDownInPage` function: it adds the current offset of the page to the target offset - which is why it ends up scrolling much more than it should.
The first time you click on a link, the `goDownInPage` function is called, while every other time the UIWebView just takes care of it - which is why all subsequent taps are ok.

I'll have to do some more testing to make sure this fix does not break something else, but here is what you can do in the meantime to fix it in your code: change line 1578 of `RootViewController.m` from

```
int targetOffset = currentPageOffset+[offset intValue];
```

to

```
int targetOffset = [offset intValue];
```

Let me know if this solves the issue for you.

**Comment by FranG** [comment]
All first and following tabs now link to the correct position! Could not seen any other issues im my demo project.
Thanks a lot!

**Comment by bahmet** [comment]
hi @Simbul ,
that modification did not solve my problem. links still go to different locations on the page
thanks

**Comment by Simbul** [comment]
We have fixed various scrolling issues in commit c33a120c751c8e87652a3a144d58e29c2ffd31eb, try it out and let us know if it solves your issue.

**Comment by Simbul** [comment]
Hi @bahmet, do you still have this issue? If not, I'll do some cleaning and close the thread.

**Comment by bahmet** [comment]
hi @Simbul , pls give me 1-2 days to test .
thanks

**Comment by bahmet** [comment]
hi @Simbul i tested the latest build c33a120 and i still have the problem. first tab to the link goes to wrong place, second one goes to the right place...
thanks

**Comment by Simbul** [comment]
We will test again. In the meantime, the Dropbox link to the page you posted in your first comment seems to be broken now. Can you upload again the page that's giving you problems?

Btw I assume you already did a cleanup. Just in case, here's how: https://github.com/Simbul/baker/wiki/Proper-cleanup

**Comment by bahmet** [comment]
http://dl.dropbox.com/u/51424384/book.rar
hi @Simbul here is the full book folder for your reference. pls note that this is for development therefore folder contains unnecessary files...
thanks

**Comment by Simbul** [comment]
Closing this as it's now extremely old. Feel free to reopen if this specific issue is still present.
